### ISSUE TITLE
Implement flat tree conversion for unbinned fits

### ISSUE THREAD

**Issue by AndrewEdmonds11** [AndrewEdmonds11/roofitter#2]
In order to use RooFit's unbinned fitting we need to convert the tree being read into a flat tree. This should be done at the start of the program before filling or fitting any data.

**Comment by lborrel** [comment]
The code I wrote creates a new tree with only the observables in it, and it also saves it in a file "trkana_flat.root". It should work for multiple observables but I haven't tried yet.

- What can we do with this tree now? All the cuts are defined using other variables, so should we change the code to use the initial tree for the cuts and the flatten tree for the observable? Or should we add all the cut variable to the flatten tree?

- Also, I think this code can be made more efficient: right now, it goes through all the entries for each observable, I think it would be more efficient to go through all the observable for each entry.

**Comment by AndrewEdmonds11** [comment]
Hi Leo

That's a good point about the cuts. I think your first idea is correct - create the flat tree after (or while) applying the cuts.

I wouldn't worry too much about optimizing things unless it significantly slows the program down. But from looking at your code, there should be a way to have two separate loops. One to create the branches and set the branch addresses; and another to loop through the TTree entries. If you want more guidance on this, then let me know :)

Cheers
Andy

**Comment by lborrel** [comment]
Hi Andy,

I figured out a way of implementing the flatten tree at the right location. It was not trivial because of how the import and cut is working currently (apply the cut on the tree as it is drawn on an histogram and then import the histogram).
My solution is to perform the cut directly on the tree using TTreeFormula, flatten the tree, and then import it for RooFit (code: https://github.com/lborrel/roofitter/commit/b94af4dd99a7bd04ee28b7d76beb3818f0e96dc0). However, by trying to do this, I stumble into a compilation error, and from the information I gathered on the root forum it comes from missing library libTreePlayer (https://root-forum.cern.ch/t/compiler-error-when-using-ttreereader/20903). I am not familiar with SCons, so I haven't found an easy way to add this library to the SConstruct file. Can you help me on this?

Thanks,
Leo

**Comment by sophiemiddleton** [comment]
Hi, 

that makes sense, sounds like good progress. I think the library is in the module "TREE" or "TREE/TREEPLAYER" so maybe add TREE into the extrarootlibs in your Scons lists (also not an expert so might be wrong).

**Comment by AndrewEdmonds11** [comment]
Hi Leo

I think Sophie's correct about the missing library. It should be added to the extrarootlibs in Main/src/SConscript.

Your code looks good to me! I have a couple of comments/requests:

 - you should be able to make that RooDataHist a RooDataSet and RooFit will do unbinned fits
 - I'd also like to keep the ability to binned fits (at least for a short while). Could you add a fcl parameter that will switch between making a RooDataHist and a RooDataSet?

Thanks
Andy

**Comment by sophiemiddleton** [comment]
yeah I think it is our plan to maintain the ability to do the binned fit while we are still in development, this should be fine with a fcl parameter as you say. We can then just switch between the two options until things progress
